---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "javadocker-deployment"
  annotations:
    description: "Provides a MongoDB database service"
labels:
  template: "javadocker-deployment-template"
objects:
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: "jd-$(ENV)"
    labels:
      app: jd
      environment: "$(ENV)"
  spec:
    replicas: $((POD_COUNT))
    selector:
      matchLabels:
        app: jd
        environment: $(ENV)
    strategy:
       type: RollingUpdate
       rollingUpdate:
         maxSurge: 1
         maxUnavailable: 1
    minReadySeconds: 20
    template:
      metadata:
        labels:
          app: jd
          environment: $(ENV)
      spec:
        containers:
        - name: javadocker
          imagePullPolicy: Never
          image: $(IMAGE)
          ports:
          - name: http
            containerPort: $((SERVER_PORT))
          env:
          - name: JAVA_OPTS
            value: "-Dserver.port=$(SERVER_PORT)"
          - name: ZK_LIST
            value: $(ZK_LIST)
          - name: ZK_CONFIG_PATH
            value: $(ZK_CONFIG_PATH)
          livenessProbe:
            httpGet:
              path: /api/greeting
              port: $((SERVER_PORT))
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/greeting
              port: $((SERVER_PORT))
            initialDelaySeconds: 5
            periodSeconds: 3
parameters:
  - name: "ENV"
    description: "environment"
    required: true
    value: "dev1"
    parameterType: "string"
  - name: "IMAGE"
    description: "docker image name"
    parameterType: "string"
    required: true
  - name: "POD_COUNT"
    description: "number of replicas"
    parameterType: "int"
    value: 2
    required: true
  - name: "SERVER_PORT"
    description: "port number"
    parameterType: "int"
    value: 8080
    required: true
  - name: "ZK_LIST"
    description: "list of zookeeper cluster hosts in connect string format (comma delimited host:ports)"
    parameterType: "string"
    required: true
  - name: "ZK_CONFIG_PATH"
    description: "zookeeper node path for config properties"
    parameterType: "string"
    required: true