---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "javadocker-deployment"
  annotations:
    description: "Provides a MongoDB database service"
labels:
  template: "javadocker-deployment-template"
objects:
-  kind: Ingress
   apiVersion: extensions/v1beta1
   metadata:
     name: jd-$(ENV)-ing
   spec:
     backend:
       serviceName: jd-$(ENV)
       servicePort: $((SERVER_PORT))
parameters:
  - name: "ENV"
    description: "environment"
    required: true
    value: "dev1"
    parameterType: "string"
  - name: "SERVER_PORT"
    description: "port number"
    parameterType: "int"
    value: 8080
    required: true