---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "javadocker-service"
  annotations:
    description: "service for javadocker app"
labels:
  template: "javadocker-deployment-template"
objects:
- kind: Service
  apiVersion: v1
  metadata:
     labels:
       app: jd
       environment: $(ENV)
  name: jd-$(ENV)-svc
  spec:
     type: NodePort
     selector:
       app: jd
       environment: $(ENV)
     ports:
     -  targetPort: $((SERVER_PORT))
        port: $((SERVER_PORT))
parameters:
  - name: "ENV"
    description: "environment"
    required: true
    value: "DEV1"
    parameterType: "string"
  - name: "SERVER_PORT"
    description: "port number"
    parameterType: "int"
    value: 8080
    required: true