kind: Service
apiVersion: v1
metadata:
  labels:
    app: jd
    stage: env1
  name: jd-env1-svc
spec:
  type: NodePort
  selector:
    app: jd
    stage: env1
  ports:
  -  targetPort: 8080 
     port: 8080 